# docker build --rm -t ambertools -f Dockerfile-amber-build .

FROM debian
MAINTAINER Andrea Giachetti <giachetti@cerm.unifi.it>
LABEL description="Build Ambertools 18"

ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
ENV AMBER_PREFIX="/usr/local/amber18"
ENV AMBERHOME="${AMBER_PREFIX}"
ENV PATH="${AMBER_PREFIX}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${AMBER_PREFIX}/lib"
ENV M2_HOME="/usr/local/apache-maven"
ENV MAVEN_HOME="/usr/local/apache-maven"
ENV  PATH="${M2_HOME}/bin:${PATH}"

RUN apt-get -y update && \
    apt-get -y install \
      openjdk-8-jdk \
      git \
      bzip2 \
      csh \
      flex \
      gfortran \
      g++ \
      libboost-dev \
      libboost-thread-dev \
      libboost-system-dev \
      libbz2-dev \
      libopenmpi-dev \
      make \
      openmpi-bin \
      patch \
      python3 \
      python3-dev \
      tar \
      xorg-dev \
      wget \
      zlib1g-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && \
    cd /usr/local && \
    wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && \
    tar xzf apache-maven-3.5.4-bin.tar.gz && \
    ln -s apache-maven-3.5.4 apache-maven && \
    rm apache-maven-3.5.4-bin.tar.gz && \
    cd /usr/local && \
    wget http://www.lip.pt/~david/ambertools/AmberTools18.tar.bz2 && \
    tar -xvf AmberTools18.tar.bz2 && \
    rm -f AmberTools18.tar.bz2 && \
    cd ${AMBER_PREFIX} && \
    ./update_amber --update && \
    ./configure --skip-python -noX11 gnu && \
    make -j8 install && \
    rm -rf ${AMBER_PREFIX}/doc \
           ${AMBER_PREFIX}/cmake \
           ${AMBER_PREFIX}/cmake-packaging \
           ${AMBER_PREFIX}/configure \
           ${AMBER_PREFIX}/logs \
           ${AMBER_PREFIX}/Makefile \
           ${AMBER_PREFIX}/share \
           ${AMBER_PREFIX}/src \
           ${AMBER_PREFIX}/AmberTools/src \
           ${AMBER_PREFIX}/AmberTools/test